export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ENTER_SUCCESS = 'ENTER_SUCCESS';
export const ENTER_FAILURE = 'ENTER_FAILURE';

export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_FAILURE = 'NOTIFY_FAILURE';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
