export const REQUEST_ONGOING_INCIDENTS = 'REQUEST_ONGOING_INCIDENTS';
export const RECEIVE_ONGOING_INCIDENTS = 'RECEIVE_ONGOING_INCIDENTS';
export const REQUEST_ONGOING_INCIDENTS_FAIL = 'REQUEST_ONGOING_INCIDENTS_FAIL';

export const REQUEST_MINE_INCIDENTS = 'REQUEST_MINE_INCIDENTS';
export const RECEIVE_MINE_INCIDENTS = 'RECEIVE_MINE_INCIDENTS';
export const REQUEST_MINE_INCIDENTS_FAIL = 'REQUEST_MINE_INCIDENTS_FAIL';

export const ACCEPT_INCIDENT_REQUEST = 'ACCEPT_INCIDENT_REQUEST';
export const ACCEPT_INCIDENT_SUCCESS = 'ACCEPT_INCIDENT_SUCCESS';
export const ACCEPT_INCIDENT_FAILURE = 'ACCEPT_INCIDENT_FAILURE';

export const RESOLVE_INCIDENT_REQUEST = 'RESOLVE_INCIDENT_REQUEST';
export const RESOLVE_INCIDENT_SUCCESS = 'RESOLVE_INCIDENT_SUCCESS';
export const RESOLVE_INCIDENT_FAILURE = 'RESOLVE_INCIDENT_FAILURE';


export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
    