export const REQUEST_ONGOING_INCIDENTS = 'REQUEST_ONGOING_INCIDENTS';
export const RECEIVE_ONGOING_INCIDENTS = 'RECEIVE_ONGOING_INCIDENTS';
export const REQUEST_ONGOING_INCIDENTS_FAIL = 'REQUEST_ONGOING_INCIDENTS_FAIL';

export const REQUEST_MINE_INCIDENTS = 'REQUEST_MINE_INCIDENTS';
export const RECEIVE_MINE_INCIDENTS = 'RECEIVE_MINE_INCIDENTS';
export const REQUEST_MINE_INCIDENTS_FAIL = 'REQUEST_MINE_INCIDENTS_FAIL';

export const ACCEPT_INCIDENT = 'ACCEPT_INCIDENT';
export const RESOLVE_INCIDENT = 'RESOLVE_INCIDENT';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
    